version: "3.9"
services:
    db:
        image: postgres:11
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - pgdata_stf365:/data/postgres
        expose:
            - 5432

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - db

    minio:
        image: minio/minio
        expose:
            - 9000
            - 9001
        volumes:
            - minio_storage:/data
        env_file:
            - .env
        command: server --console-address ":9001" /data


volumes:
    pgdata_stf365:
    minio_storage: